* Magellan

A Clojure library for interacting with [[https://geotools.org/][GeoTools]], an open source Java library that provides tools for geospatial data.

** Useful Aliases
*** To build the (library) JAR run:

#+BEGIN_SRC sh
clojure -A:make-jar
#+END_SRC

*** To deploy the JAR to clojars.org run:

*Note*: Make sure to build the library first.

First create a pom.xml file if you don't already have one.

#+BEGIN_SRC sh
clojure -Spom
#+END_SRC

Then to deploy run:

#+BEGIN_SRC sh
env CLOJARS_USERNAME=your-username CLOJARS_PASSWORD=your-clojars-token clojure -A:deploy
#+END_SRC

**** A note on Clojars tokens:
     
As of 2020-06-27, Clojars will no longer accept your Clojars password when
deploying. You will have to use a token instead. Please read more about this [[https://github.com/clojars/clojars-web/wiki/Deploy-Tokens][here]].

*** To check for outdated dependencies run:

#+BEGIN_SRC sh
clojure -A:check-deps
#+END_SRC

*** To launch the test suite run:
    
#+BEGIN_SRC sh
clojure -A:test
#+END_SRC

** License

 Copyright © 2011-2020 Spatial Informatics Group, LLC.

 GridFire is distributed by Spatial Informatics Group, LLC. under the
 terms of the Eclipse Public License version 2.0 (EPLv2). See
 LICENSE.txt in this directory for more information.
