* Magellan

A Clojure library for interacting with [[https://geotools.org/][GeoTools]], an open source Java
library that provides tools for geospatial data.

** Useful Aliases
*** check-deps

To check for outdated dependencies, run:

#+begin_src sh
clojure -M:check-deps
#+end_src

Remember to update deps.edn with any new versions that are found.

*** deploy-jar

To build a JAR from this library and deploy it to clojars.org, run:

#+begin_src sh
env CLOJARS_USERNAME=your-username CLOJARS_PASSWORD=your-clojars-token clojure -M:deploy-jar
#+end_src

NOTE: As of 2020-06-27, Clojars will no longer accept your Clojars
password when deploying. You will have to use a token instead. Please
read more about this [[https://github.com/clojars/clojars-web/wiki/Deploy-Tokens][here]].

*** test

To launch the test suite, run:
    
#+begin_src sh
clojure -M:test
#+end_src

** License

Copyright © 2011-2021 Spatial Informatics Group, LLC.

Magellan is distributed by Spatial Informatics Group, LLC. under the
terms of the Eclipse Public License version 2.0 (EPLv2). See
LICENSE.txt in this directory for more information.
