name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: tools.deps-builder
      # You may pin to the exact commit or the version.
      uses: vouch-opensource/tools.deps-build@aa0b444776fc18fa431567e93c46045dece05fd2
